"""empty message

Revision ID: 16aada31bd7d
Revises: f45379ce13ec
Create Date: 2018-06-05 08:37:42.191210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16aada31bd7d'
down_revision = 'f45379ce13ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('approval_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'approval_date')
    # ### end Alembic commands ###
