"""empty message

Revision ID: 25a04178f419
Revises: b96020120e08
Create Date: 2018-05-08 20:48:23.224219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a04178f419'
down_revision = 'b96020120e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('light_noted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'light_noted')
    # ### end Alembic commands ###
