"""empty message

Revision ID: 479d452e9e27
Revises: ef9456cdb62d
Create Date: 2018-08-01 15:04:57.126677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479d452e9e27'
down_revision = 'ef9456cdb62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('invoice_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'invoice_num')
    # ### end Alembic commands ###
