"""empty message

Revision ID: 5ddcd95c6db0
Revises: 25a04178f419
Create Date: 2018-05-11 09:16:14.981742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddcd95c6db0'
down_revision = '25a04178f419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('approval_date', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('induction_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'induction_date')
    op.drop_column('order', 'approval_date')
    # ### end Alembic commands ###
