"""empty message

Revision ID: 656bac90a595
Revises: 32495528e9cd
Create Date: 2018-05-13 19:44:56.760116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656bac90a595'
down_revision = '32495528e9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
