"""empty message

Revision ID: 6e01628c35e9
Revises: 656bac90a595
Create Date: 2018-05-13 20:17:01.906015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e01628c35e9'
down_revision = '656bac90a595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('approval_type', sa.String(length=32), nullable=True))
    op.drop_column('order', 'po_light')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('po_light', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('order', 'approval_type')
    # ### end Alembic commands ###
