"""empty message

Revision ID: b8be05558079
Revises: 479d452e9e27
Create Date: 2019-02-08 11:07:39.510662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8be05558079'
down_revision = '479d452e9e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('interchange', sa.String(length=128), nullable=True))
    op.add_column('order', sa.Column('swap_out', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('tested_bare', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'tested_bare')
    op.drop_column('order', 'swap_out')
    op.drop_column('order', 'interchange')
    # ### end Alembic commands ###
