"""empty message

Revision ID: ef9456cdb62d
Revises: 16aada31bd7d
Create Date: 2018-06-18 11:54:15.856768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9456cdb62d'
down_revision = '16aada31bd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('light_type_comments', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'light_type_comments')
    # ### end Alembic commands ###
