"""empty message

Revision ID: f45379ce13ec
Revises: b390b1a179ec
Create Date: 2018-06-04 09:18:39.876904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45379ce13ec'
down_revision = 'b390b1a179ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_images')
    op.add_column('image', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'image', 'order', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'parent_id')
    op.create_table('order_images',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name='order_images_image_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_images_order_id_fkey')
    )
    # ### end Alembic commands ###
